java.util.UUID
tiny-express/native pull request #116
Opened 2017-07-03 02:59 UTC by neacao

Completed implement functions inside UUID.

2017-07-03 06:26 UTC, frangte requested changes

2017-07-03 06:26 UTC, frangte commented on java/util/UUID/UUID.hpp
>               * @return
Missing  type variable return

2017-07-03 06:26 UTC, Frangte commented on java/util/UUID/UUID.cpp
>      long msb = 0;
Please set variable name  easy to understand.

2017-07-03 15:58 UTC, loint submitted a review, later dismissed
PR should be rejected because of comments below

2017-07-04 07:21 UTC, dthongvl reviewed
Tu Boi testing

2017-07-04 07:21 UTC, dthongvl commented on java/util/UUID/UUID.cpp
> +    long hi = 1L << (digit * 4);
Please rename hi to high

2017-07-04 07:21 UTC, dthongvl commented on java/util/UUID/UUID.cpp
>      for (int i = 0; i < 8; ++i) {
Please create **int i** outside the loop and rename it to index or something make sense
and reuse it in next loop
https://github.com/foodtiny/native/blob/master/CONTRIBUTION.md

2017-07-04 07:21 UTC, dthongvl commented on java/util/UUID/UUID.cpp
> + * @return int
Please add comment about the return value 1, -1, 0 or define const

2017-07-04 07:21 UTC, dthongvl commented on java/util/UUID/UUID.cpp
>      long hilo = this->mostSigBits ^ this->leastSigBits;
Please rename hilo T.T

2017-07-04 07:21 UTC, dthongvl commented on java/util/UUID/UUID.cpp
> +    for (int i=0; i<5; i++)
Create **int i** ouside loop

2017-07-05 07:25 UTC, dthongvl requested changes
Please implement public int clockSequence()

2017-07-05 07:25 UTC, dthongvl commented on java/util/UUID/UUID.cpp
> +    for (int i = 0; i < 16; ++i) {
Please change this

2017-07-06 12:30 UTC, dthongvl approved these changes
Approved

2017-07-06 12:34 UTC, frangte approved these changes

2017-07-06 12:34 UTC, merged