Java.Util.PriorityQueue
tiny-express/native pull request #184
Opened 2017-07-21 04:54 UTC by truongchauhien

2017-07-21 14:32 UTC, dthongvl requested changes

2017-07-21 14:32 UTC, dthongvl commented on java/lang/ClassCastException/ClassCastExceptionTest.cpp
> +    catch (Exception ex) {
Please catch ClassCastException

2017-07-21 14:32 UTC, dthongvl commented on java/util/PriorityQueue/PriorityQueueTest.cpp
> +TEST(JavaUtil, PriorityQueueDestructor) {
Please remove test if it doesnt have ASSERT statement.

2017-07-21 14:32 UTC, dthongvl commented on java/util/PriorityQueue/PriorityQueue.hpp
> +//          PriorityQueue(int initialCapacity);
Why this constructor is disabled?

2017-07-21 22:10 UTC, truongchauhien commented on java/util/PriorityQueue/PriorityQueueTest.cpp
> +TEST(JavaUtil, PriorityQueueDestructor) {
Done.

2017-07-21 22:15 UTC, truongchauhien commented on java/lang/ClassCastException/ClassCastExceptionTest.cpp
> +    catch (Exception ex) {
Done.

2017-07-21 22:49 UTC, truongchauhien commented on java/util/PriorityQueue/PriorityQueue.hpp
> +//          PriorityQueue(int initialCapacity);
I have enabled it, but I can only test this constructor with `initialCapacity < 1` to throw exception. PriorityQueue class doesn't have "getCapacity" (or similar) method and std::vector<T> doesn't have any method to control exactly initialCapacity.
We use this constructor to ensure that PriorityQueue instance has "enough capacity" (>= initialCapacity argument) as we want.

2017-07-22 18:14 UTC, dthongvl approved these changes

2017-07-22 18:14 UTC, merged