Java.Util.ArrayList
tiny-express/native pull request #200
Opened 2017-07-25 18:11 UTC by Frangte

2017-07-26 02:30 UTC, thoangminh commented
Please check my comment in channel #review. :)

2017-07-26 02:31 UTC, ghost requested changes
Please check my comment in channel #review. :)

2017-08-06 11:42 UTC, ghost submitted a review, later dismissed

2017-08-06 11:42 UTC, thoangminh commented on java/util/ArrayList/ArrayList.hpp
> +				// TODO: Please discuss about param Collection
You can replace TODO by TODO(your name) to let people know this is your TODO.

2017-08-06 11:42 UTC, thoangminh commented on java/util/ArrayList/ArrayList.hpp
> +				// TODO: Please discuss about param Collection
You can replace TODO by TODO(your name) to let people know this is your TODO.

2017-08-06 11:42 UTC, thoangminh commented on java/util/ArrayList/ArrayList.hpp
> +				// TODO: Please discuss about param Collection
You can replace TODO by TODO(your name) to let people know this is your TODO.

2017-08-06 11:42 UTC, thoangminh commented on java/util/ArrayList/ArrayList.hpp
> +                // TODO: Please complete class Consumer
You can replace TODO by TODO(your name) to let people know this is your TODO.

2017-08-06 11:42 UTC, thoangminh commented on java/util/ArrayList/ArrayList.hpp
> +                // TODO: Please complete class Iterator
You can replace TODO by TODO(your name) to let people know this is your TODO.

2017-08-06 11:42 UTC, thoangminh commented on java/util/ArrayList/ArrayList.hpp
> +                // TODO: Please discuss about param Collection
You can replace TODO by TODO(your name) to let people know this is your TODO.

2017-08-06 11:42 UTC, thoangminh commented on java/util/ArrayList/ArrayList.hpp
> +                // TODO: Please complete class Predicate
You can replace TODO by TODO(your name) to let people know this is your TODO.

2017-08-06 11:42 UTC, thoangminh commented on java/util/ArrayList/ArrayList.hpp
> +                // TODO: Please complete class UnaryOperator
You can replace TODO by TODO(your name) to let people know this is your TODO.

2017-08-06 11:42 UTC, thoangminh commented on java/util/ArrayList/ArrayList.hpp
> +                // TODO: Please discuss about Param Collection
You can replace TODO by TODO(your name) to let people know this is your TODO.

2017-08-06 11:42 UTC, thoangminh commented on java/util/ArrayList/ArrayList.hpp
> +                // TODO: Please complete class Comparator
You can replace TODO by TODO(your name) to let people know this is your TODO.

2017-08-06 11:42 UTC, thoangminh commented on java/util/ArrayList/ArrayList.hpp
> +                // TODO: Please complete class Spliterator
You can replace TODO by TODO(your name) to let people know this is your TODO.

2017-08-06 11:42 UTC, thoangminh commented on java/util/ArrayList/ArrayList.hpp
> +            // TODO: Please discuss about param Object
You can replace TODO by TODO(your name) to let people know this is your TODO.

2017-08-06 11:42 UTC, thoangminh commented on java/util/ArrayList/ArrayList.hpp
> +				this->original.erase(this->original.begin() + fromIndex, this->begin() + toIndex);
Please plit or shorten this line. Your code style will be better :)

2017-08-09 04:46 UTC, dthongvl approved these changes

2017-08-09 04:47 UTC, merged