Java.Util.Base64
tiny-express/native pull request #205
Opened 2017-07-29 21:46 UTC by truongchauhien

2017-07-29 23:28 UTC, ghost requested changes

2017-07-29 23:28 UTC, ghost commented on java/util/Base64/Base64.cpp
> +    int destinationLength = this->encoding(source, 0, source.length, destination);
Please shoten or split this line !

2017-07-29 23:28 UTC, ghost commented on java/util/Base64/Base64.cpp
> +        throw IllegalArgumentException("Output byte array is too small for encoding all input bytes");
Please shoten or split this line !

2017-07-29 23:28 UTC, ghost commented on java/util/Base64/Base64.cpp
> +    // If there are only 1 or 2 bytes in a block (at the end), they will be processed later.
Please shoten or split this line !

2017-07-29 23:28 UTC, ghost commented on java/util/Base64/Base64.cpp
> +    // Change lineMax (number of base64 digit per line) to equivalent length of source.
Please shoten or split this line !

2017-07-29 23:28 UTC, ghost commented on java/util/Base64/Base64.cpp
> +    // Length of source will be encoded into ONE line of base64 "string" (depending on Base64 scheme).
Please shoten or split this line !

2017-07-29 23:28 UTC, ghost commented on java/util/Base64/Base64.cpp
> +    int chunksOfSourceLength = sourceLength; // Don't have linemax condition.
We need at least two space between code and comment.

2017-07-29 23:28 UTC, ghost commented on java/util/Base64/Base64.cpp
> +    if (this->lineMax > 0 && sourceLength > base64LineMaxToEquivalentSourceLength) {
Please shoten or split this line !

2017-07-29 23:28 UTC, ghost commented on java/util/Base64/Base64.cpp
> +             chunksOfSourceWillBeEncodedPosition < chunksOfSourceWillBeEncodedPausePosition;) {
Please shoten or split this line !

2017-07-29 23:28 UTC, ghost commented on java/util/Base64/Base64.cpp
> +                    static_cast<byte>(base64IndexTable[(firstByte << 4) & 0x3f | (secondByte >> 4)]);
Please shoten or split this line !

2017-07-29 23:28 UTC, ghost commented on java/util/Base64/Base64.cpp
> +Base64::Decoder Base64::Decoder::RFC4648_URLSAFE = Base64::Decoder(true,  false);
Please shoten or split this line !

2017-07-29 23:28 UTC, ghost commented on java/util/Base64/Base64.cpp
> +    int destinationLength = this->decoding(source, 0, source.length, destination);
Please shoten or split this line !

2017-07-29 23:28 UTC, ghost commented on java/util/Base64/Base64.cpp
> +        throw IllegalArgumentException("Output byte array is too small for decoding all input bytes");
Please shoten or split this line !

2017-07-29 23:28 UTC, ghost commented on java/util/Base64/Base64.cpp
> +        throw IllegalArgumentException("Input byte[] should at least have 2 bytes for based64 bytes");
Please shoten or split this line !

2017-07-29 23:28 UTC, ghost commented on java/util/Base64/Base64.cpp
> +        if (currentByteDecoded < 0) { // Means non-Alphabet (CRLF or line separator) or padding '='.
We need at least two space between code and comment.
Please shoten or split this line !

2017-07-29 23:28 UTC, ghost commented on java/util/Base64/Base64.cpp
> +            if (currentByteDecoded == -2) { // Current byte is '=': padding byte
We need at least two space between code and comment.

2017-07-29 23:28 UTC, thoangminh commented on java/util/Base64/Base64.cpp
> +        if (currentByteDecoded < 0) {  // Means non-Alphabet (CRLF or line separator) or padding '='.
Please shoten or split this line !

2017-07-29 23:28 UTC, thoangminh commented on java/util/Base64/Base64.cpp
> +            if (currentByteDecoded == -2) {  // Current byte is '=': padding byte
Please shoten or split this line !

2017-07-29 23:28 UTC, thoangminh commented on java/util/Base64/Base64.cpp
> +                    && (sourcePosition == sourceStopPosition || source[sourcePosition++] != '=')
Please shoten or split this line !

2017-07-29 23:28 UTC, thoangminh commented on java/util/Base64/Base64.cpp
> +                    // shiftTo == 18 ........................................ => '=' at wrong position.
Please shoten or split this line !

2017-07-29 23:28 UTC, thoangminh commented on java/util/Base64/Base64.cpp
> +                    // shiftTo == 6 && sourcePosition == sourceStopPosition . => Second '=' is missing.
Please shoten or split this line !

2017-07-29 23:28 UTC, thoangminh commented on java/util/Base64/Base64.cpp
> +                    // shiftTo == 6 && source[sourcePosition++] != '=' ...... => Byte after first '=' doesn't present for '='.
Please shoten or split this line !

2017-07-29 23:28 UTC, thoangminh commented on java/util/Base64/Base64.hpp
> +                // TODO (truongchauhien): Waiting for ByteBuffer class.
Should be // TODO(truongchauhien) :D

2017-07-29 23:28 UTC, thoangminh commented on java/util/Base64/Base64.hpp
> +                // TODO (truongchauhien): Waiting for OutputStream class.
Should be // TODO(truongchauhien) :D

2017-07-29 23:28 UTC, thoangminh commented on java/util/Base64/Base64.hpp
> +            }; // class Encoder
We need at least two space is best between code and comments. :)

2017-07-29 23:28 UTC, thoangminh commented on java/util/Base64/Base64Test.cpp
> +        ASSERT_STR("Output byte array is too small for encoding all input bytes",
You can shorten or split this line. I think it will be better for looking :D

2017-07-29 23:28 UTC, thoangminh commented on java/util/Base64/Base64Test.cpp
> +    Base64::Encoder mimeEncoder = Base64::getMimeEncoder(); // RFC2045
At least two space between code and comment is best. You should try :)

2017-07-29 23:28 UTC, thoangminh commented on java/util/Base64/Base64Test.cpp
> +    int maximumNumberOfCharacterOnALine = 76; // don't sum length of line separator.
At least two space between code and comment is best. You should try :)

2017-07-29 23:28 UTC, thoangminh commented on java/util/Base64/Base64Test.cpp
> +             'F', 'h', 'Y', 'W', 'F', 'h', '@', '#', // '@' as 77, '#' as 88.
At least two space between code and comment is best. You should try :)

2017-07-29 23:28 UTC, thoangminh commented on java/util/Base64/Base64Test.cpp
> +    Base64::Decoder basicDecoder = Base64::getDecoder(); // RFC4648
At least two space between code and comment is best. You should try :)

2017-07-29 23:28 UTC, thoangminh commented on java/util/Base64/Base64Test.cpp
> +    Array<byte> inputWithoutPadding = {'T', 'W', 'E'};  // ... with padding {'T', 'W', 'E', '='}
You can shorten or split this line. I think it will be better for looking :D

2017-07-29 23:28 UTC, thoangminh commented on java/util/Base64/Base64Test.cpp
> +        ASSERT_STR("Output byte array is too small for decoding all input bytes",
You can shorten or split this line. I think it will be better for looking :D

2017-07-29 23:28 UTC, thoangminh commented on java/util/Base64/Base64Test.cpp
> +    for (index = 0; index < outputArray.length; index++) { // Filling with '*'.
At least two space between code and comment is best. You should try :)

2017-07-29 23:28 UTC, thoangminh commented on java/util/Base64/Base64Test.cpp
> +             ' ', 'V', 'i', 'e', 't', 'n', 'a', 'm', '!'}; // "Welcome to Vietnam!"
At least two space between code and comment is best. You should try :)
You can shorten or split this line. I think it will be better for looking :D

2017-07-30 07:17 UTC, truongchauhien commented on java/util/Base64/Base64Test.cpp
> +        ASSERT_STR("Output byte array is too small for decoding all input bytes",
I have splitted it.
```
ASSERT_STR("Output byte array is too small for decoding all input bytes",
                   ex.getMessage().toString());
```

2017-07-30 07:18 UTC, truongchauhien commented on java/util/Base64/Base64Test.cpp
> +    Array<byte> inputWithoutPadding = {'T', 'W', 'E'};  // ... with padding {'T', 'W', 'E', '='}
I don't split this line, because it will be hard to understand.

2017-07-30 07:21 UTC, truongchauhien commented on java/util/Base64/Base64Test.cpp
> +        ASSERT_STR("Output byte array is too small for encoding all input bytes",
I have splitted this line.
```cpp
ASSERT_STR("Output byte array is too small for encoding all input bytes",
                   ex.getMessage().toString());
```

2017-07-30 07:25 UTC, truongchauhien commented on java/util/Base64/Base64.cpp
> +             chunksOfSourceWillBeEncodedPosition < chunksOfSourceWillBeEncodedPausePosition;) {
It will be hard to understand.

2017-07-30 07:26 UTC, truongchauhien commented on java/util/Base64/Base64.cpp
> +                    static_cast<byte>(base64IndexTable[(firstByte << 4) & 0x3f | (secondByte >> 4)]);
I will be hard to understand.

2017-07-30 07:26 UTC, truongchauhien commented on java/util/Base64/Base64.cpp
> +    int destinationLength = this->decoding(source, 0, source.length, destination);
I don't see any line need to split at here.

2017-07-30 07:26 UTC, truongchauhien commented on java/util/Base64/Base64.cpp
> +        if (currentByteDecoded < 0) {  // Means non-Alphabet (CRLF or line separator) or padding '='.
It will be hard to understand.

2017-07-30 07:27 UTC, truongchauhien commented on java/util/Base64/Base64.cpp
> +            if (currentByteDecoded == -2) {  // Current byte is '=': padding byte
It will be hard to understand.

2017-07-30 07:28 UTC, truongchauhien commented on java/util/Base64/Base64.cpp
> +    // Change lineMax (number of base64 digit per line) to equivalent length of source.
Shouldn't split that comment.

2017-07-30 07:28 UTC, truongchauhien commented on java/util/Base64/Base64.cpp
> +    // Length of source will be encoded into ONE line of base64 "string" (depending on Base64 scheme).
Shouldn't split that comments.

2017-07-30 07:28 UTC, truongchauhien commented on java/util/Base64/Base64.cpp
> +    // If there are only 1 or 2 bytes in a block (at the end), they will be processed later.
Shouldn't split that comments.

2017-07-30 07:29 UTC, truongchauhien commented on java/util/Base64/Base64.cpp
> +    int destinationLength = this->encoding(source, 0, source.length, destination);
I think that lines are fine.

2017-07-30 08:24 UTC, ghost approved these changes

2017-07-30 08:49 UTC, merged