Java.Lang.Math
tiny-express/native pull request #211
Opened 2017-08-02 15:35 UTC by TuanAnhNguyen69

2017-08-02 16:13 UTC, dthongvl requested changes

2017-08-02 16:13 UTC, dthongvl commented on java/lang/ArithmeticException/ArithmeticException.hpp
> +        //TODO change to RuntimeException when merge
Please change bro

2017-08-02 16:13 UTC, dthongvl commented on java/lang/ArithmeticException/ArithmeticExceptionTest.cpp
> +    } catch (Exception e) {
Please catch ArithmeticException &

2017-08-02 16:13 UTC, dthongvl commented on java/lang/Integer/Integer.hpp
> +			 *A constant holding the minimum value an int can have, -2^31.
Add space

2017-08-02 16:13 UTC, dthongvl commented on java/lang/Float/Float.hpp
> +             *             The number of bytes used to represent a float value.
Please remove space

2017-08-02 16:13 UTC, dthongvl commented on java/lang/Math/Math.cpp
> +double Math::asin(double a) {
Please change a to value

2017-08-02 16:13 UTC, dthongvl commented on java/lang/Math/Math.cpp
> +    } else {
We dont need else here

2017-08-02 16:13 UTC, dthongvl commented on java/lang/Math/Math.cpp
> +        } else {
And here

2017-08-02 16:13 UTC, dthongvl commented on java/lang/Math/Math.cpp
> +    } else {
Here too

2017-08-02 16:13 UTC, dthongvl commented on java/lang/Math/Math.cpp
> +    return (a == 0.0 || Double::isNaN(a)) ? a: copySign(1.0, a);
Please rewrite with full if

2017-08-02 16:13 UTC, dthongvl commented on java/lang/Math/Math.cpp
> +                // TODO Throw Assertion error
Please throw

2017-08-02 16:16 UTC, TuanAnhNguyen69 commented on java/lang/Math/Math.cpp
> +                // TODO Throw Assertion error
AssertionError is not available

2017-08-02 17:17 UTC, dthongvl commented on java/lang/Math/Math.cpp
> +                // TODO Throw Assertion error
Create :v:

2017-08-04 12:48 UTC, dthongvl requested changes

2017-08-04 12:48 UTC, dthongvl commented on java/lang/Math/Math.cpp
> +    return Double::longBitsToDouble((((long) exponent + (long) Double::EXP_BIAS)
are there anyway to shorten this?

2017-08-04 12:48 UTC, dthongvl commented on java/lang/Math/Math.hpp
> +             * @return a if a is positive, else -a
Please fix this

2017-08-04 12:48 UTC, dthongvl commented on java/lang/Math/Math.hpp
> +             * @return the value (e^a),
Please fix this

2017-08-04 12:48 UTC, dthongvl commented on kernel/math.h
> +double math_round(double a);
Please rename a tooooooo

2017-08-04 18:02 UTC, dthongvl requested changes

2017-08-04 18:02 UTC, dthongvl commented on java/lang/Math/Math.hpp
> +             * @return he floor modulus of the arguments
the

2017-08-05 04:24 UTC, dthongvl approved these changes

2017-08-05 04:24 UTC, merged