Java.Net.URLEncoder/URLDecoder
tiny-express/native pull request #218
Opened 2017-08-08 02:57 UTC by truongchauhien

2017-08-08 04:05 UTC, dthongvl requested changes

2017-08-08 04:05 UTC, dthongvl commented on java/io/IOException/IOExceptionTest.cpp
>      } catch (Exception e) {
Please catch **IOException &**

2017-08-08 04:05 UTC, dthongvl commented on java/io/UnsupportedEncodingException/UnsupportedEncodingExceptionTest.cpp
> +    } catch (UnsupportedEncodingException ex) {
You can improve with catch by reference

2017-08-08 04:05 UTC, dthongvl commented on java/lang/Long/Long.cpp
> +    y = static_cast<int>(i); if (y != 0) { n = n -32; x = y; }
Please help me fix this style

2017-08-08 04:05 UTC, dthongvl commented on java/lang/Long/Long.cpp
> +    if (i == 0) return 64;
Please use bracket

2017-08-08 04:05 UTC, dthongvl commented on java/util/BitSet/BitSet.cpp
> +        throw IndexOutOfBoundsException(String("fromIndex < 0: ") +
Is there anyway to shorten this? I think it would be great if you do that

2017-08-08 05:04 UTC, truongchauhien commented on java/util/BitSet/BitSet.cpp
> +        throw IndexOutOfBoundsException(String("fromIndex < 0: ") +
Fixed, thanks!

2017-08-08 05:10 UTC, truongchauhien commented on java/io/UnsupportedEncodingException/UnsupportedEncodingExceptionTest.cpp
> +    } catch (UnsupportedEncodingException ex) {
OK, I will remember this tip, thanks!

2017-08-08 05:10 UTC, truongchauhien commented on java/io/IOException/IOExceptionTest.cpp
>      } catch (Exception e) {
Fixed, thanks!

2017-08-08 05:58 UTC, dthongvl requested changes

2017-08-08 05:58 UTC, dthongvl commented on java/util/BitSet/BitSet.cpp
> +    if (this->words.length < wordsRequired) {
Please use early return

2017-08-08 05:58 UTC, dthongvl commented on java/net/URLEncoder/URLEncoderTest.cpp
> +TEST(JavaNet, URLEncodeString) {
I think you should divide into 2 test cases
EncodeString and EncodeStringWithEncoding or something

2017-08-08 05:58 UTC, dthongvl commented on java/util/BitSet/BitSet.cpp
> +    checkRange(fromIndex, toIndex);
Please help me add **this->**

2017-08-08 05:58 UTC, dthongvl commented on java/util/BitSet/BitSet.cpp
> +    int startWordIndex = wordIndex(fromIndex);
Please help me add **this->**

2017-08-08 06:21 UTC, truongchauhien commented on java/util/BitSet/BitSet.cpp
> +    int startWordIndex = wordIndex(fromIndex);
Because `wordIndex` is a private static method, so should we use `this->`?

2017-08-08 06:30 UTC, dthongvl commented on java/util/BitSet/BitSet.cpp
> +    int startWordIndex = wordIndex(fromIndex);
I think we use **this->** to show that it's not from outside class

2017-08-08 06:32 UTC, truongchauhien commented on java/util/BitSet/BitSet.cpp
> +    int startWordIndex = wordIndex(fromIndex);
OK, thanks! Fixed!

2017-08-08 06:41 UTC, truongchauhien commented on java/util/BitSet/BitSet.cpp
> +    if (this->words.length < wordsRequired) {
Fixed! Thanks!

2017-08-08 06:42 UTC, truongchauhien commented on java/util/BitSet/BitSet.cpp
> +    checkRange(fromIndex, toIndex);
Fixed! Thanks!

2017-08-08 06:47 UTC, truongchauhien commented on java/net/URLEncoder/URLEncoderTest.cpp
> +TEST(JavaNet, URLEncodeString) {
OK, thanks!

2017-08-08 13:18 UTC, truongchauhien commented on java/lang/Long/Long.cpp
> +    if (i == 0) return 64;
Fixed.

2017-08-08 13:18 UTC, truongchauhien commented on java/lang/Long/Long.cpp
> +    y = static_cast<int>(i); if (y != 0) { n = n -32; x = y; }
Fixed.

2017-08-09 08:18 UTC, dthongvl approved these changes

2017-08-09 08:18 UTC, merged