#114 Implement String::format() with POSIX regex functions
tiny-express/native pull request #228
Opened 2017-08-16 13:51 UTC by sonda2208

2017-08-20 09:55 UTC, ghost requested changes

2017-08-20 09:55 UTC, ghost commented on java/lang/String/String.cpp
> +    if(length > 0)
Please add space before ( in if(

2017-08-20 09:55 UTC, thoangminh commented on java/lang/String/String.cpp
> +{
{ should almost always be at the end of the previous line. We follow the google code style for C++.

2017-08-20 09:55 UTC, thoangminh commented on java/lang/String/String.cpp
> +{
{ should almost always be at the end of the previous line. We follow the google code style for C++.

2017-08-20 09:55 UTC, thoangminh commented on java/lang/String/String.cpp
> +{
{ should almost always be at the end of the previous line. We follow the google code style for C++.

2017-08-20 09:55 UTC, thoangminh commented on java/lang/String/String.cpp
> +{
{ should almost always be at the end of the previous line. We follow the google code style for C++.

2017-08-20 09:55 UTC, thoangminh commented on java/lang/String/String.cpp
> +{
{ should almost always be at the end of the previous line. We follow the google code style for C++.

2017-08-20 09:55 UTC, thoangminh commented on java/lang/String/String.cpp
> +{
{ should almost always be at the end of the previous line. We follow the google code style for C++.

2017-08-20 09:55 UTC, thoangminh commented on java/lang/String/String.cpp
> +{
{ should almost always be at the end of the previous line. We follow the google code style for C++.

2017-08-20 09:55 UTC, thoangminh commented on java/lang/String/String.cpp
> +{
{ should almost always be at the end of the previous line. We follow the google code style for C++.

2017-08-20 09:55 UTC, thoangminh commented on java/lang/String/String.cpp
> +{
{ should almost always be at the end of the previous line. We follow the google code style for C++.

2017-08-20 09:55 UTC, thoangminh commented on java/lang/String/String.cpp
> +{
{ should almost always be at the end of the previous line. We follow the google code style for C++.

2017-08-20 09:55 UTC, thoangminh commented on java/lang/String/String.cpp
> +{
Please place the { after the method name. We follow the google code style for C++.

2017-08-20 09:55 UTC, thoangminh commented on java/lang/String/String.cpp
> +{
{ should almost always be at the end of the previous line. We follow the google code style for C++.

2017-08-20 09:55 UTC, thoangminh commented on java/lang/String/String.cpp
> +{
Please place the { after the method name. We follow the google code style for C++.

2017-08-20 09:55 UTC, thoangminh commented on java/lang/String/String.cpp
> +{
{ should almost always be at the end of the previous line. We follow the google code style for C++.

2017-08-20 09:55 UTC, thoangminh commented on java/lang/String/String.cpp
> +{
Please place the { after the method name. We follow the google code style for C++.

2017-08-20 09:55 UTC, thoangminh commented on java/lang/String/String.cpp
> +{
{ should almost always be at the end of the previous line. We follow the google code style for C++.

2017-08-20 09:55 UTC, thoangminh commented on java/lang/String/String.cpp
> +    if(length > 0)
Please add space before ( in if(

2017-08-20 09:55 UTC, thoangminh commented on java/lang/String/String.cpp
> +    if(length > 0)
Please add space before ( in if(

2017-08-20 09:55 UTC, thoangminh commented on java/lang/String/String.cpp
> +    if(length > 0)
Please add space before ( in if(

2017-08-20 09:55 UTC, thoangminh commented on java/lang/String/String.cpp
> +    if(length > 0)
Please add space before ( in if(

2017-08-20 09:55 UTC, thoangminh commented on java/lang/String/String.cpp
> +    if(length > 0)
Please add space before ( in if(

2017-08-20 09:55 UTC, thoangminh commented on java/lang/String/String.cpp
> +    if(length > 0)
Please add space before ( in if(

2017-08-20 09:55 UTC, thoangminh commented on java/lang/String/String.cpp
> +    if(length > 0)
Please add space before ( in if(

2017-08-20 09:55 UTC, thoangminh commented on java/lang/String/String.cpp
> +    if(length > 0)
Please add space before ( in if(

2017-08-20 09:55 UTC, thoangminh commented on java/lang/String/String.cpp
> +    while(errorCode == 0 && inputStringOffset < inputString.getSize()) {
Missing space before ( in while(

2017-08-20 09:55 UTC, thoangminh commented on java/lang/String/String.cpp
> +        regmatch_t matchedResult[16] = {0}; // max 16 groups
At least two spaces is best between code and comments

2017-08-20 09:55 UTC, thoangminh commented on java/lang/String/String.cpp
> +                else
An else should appear on the same line as the preceding }

2017-08-20 09:55 UTC, thoangminh commented on java/lang/String/String.hpp
> +                while(errorCode == 0 && inputStringOffset < inputString.getSize()) {
Missing space before ( in while(

2017-08-20 09:55 UTC, thoangminh commented on java/lang/String/String.hpp
> +                    regmatch_t matchedResult[16] = {0}; // max 16 groups
At least two spaces is best between code and comments

2017-08-20 09:55 UTC, thoangminh commented on java/lang/String/String.hpp
> +                    if(errorCode == 0) {
Missing space before ( in if(

2017-08-20 09:55 UTC, thoangminh commented on java/lang/String/String.hpp
> +                        if(unmatchedStringLength > 0)
Missing space before ( in if(

2017-08-20 09:55 UTC, thoangminh commented on java/lang/String/String.hpp
> +                        if(matchedStringLength > 0) {
Missing space before ( in if(

2017-08-20 09:55 UTC, thoangminh commented on java/lang/String/String.hpp
> +                            if(matchedString.charAt(matchedString.getSize() - 1) != '%') {
Missing space before ( in if(

2017-08-20 09:55 UTC, thoangminh commented on java/lang/String/String.hpp
> +            };
You don’t need a ; after a }

2017-08-20 09:55 UTC, thoangminh commented on java/lang/String/String.hpp
> +                if(format.getSize() > 0)
Missing space before ( in if(

2017-08-20 09:55 UTC, thoangminh commented on java/lang/String/String.hpp
> +                switch(lastChar) {
Missing space before ( in switch(

2017-08-20 09:55 UTC, thoangminh commented on java/lang/String/String.hpp
> +	}
Namespace should be terminated with "// namespace Lang"

2017-08-20 09:55 UTC, thoangminh commented on java/lang/String/StringTest.cpp
> +    string stringValue = "string";
Please catch string type for this value

2017-08-20 09:55 UTC, thoangminh commented on java/lang/String/String.cpp
> +String::String(string original, int length) {
Please add test case for String::String(string original, int length) in TEST (JavaLang, StringConstructor)

2017-08-20 09:55 UTC, thoangminh commented on java/lang/String/String.cpp
> +String String::print(const String &format, short value)
Please add test case for String String::print(const String &format, short value) in TEST(JavaLang, StringFormat)

2017-08-20 09:55 UTC, thoangminh commented on java/lang/String/String.cpp
> +String String::print(const String &format, unsigned short value)
Please add test case for String String::print(const String &format, unsigned short value) in TEST(JavaLang, StringFormat)

2017-08-20 09:55 UTC, thoangminh commented on java/lang/String/String.cpp
> +String String::print(const String &format, unsigned int value)
Please add test case for String String::print(const String &format, unsigned int value) in TEST(JavaLang, StringFormat)

2017-08-20 09:55 UTC, thoangminh commented on java/lang/String/String.cpp
> +String String::print(const String &format, unsigned long value)
Please add test case for String String::print(const String &format, unsigned long value) in TEST(JavaLang, StringFormat)

2017-08-20 09:55 UTC, thoangminh commented on java/lang/String/String.cpp
> +String String::print(const String &format, Short value)
Please add test case for String String::print(const String &format, Short value) in TEST(JavaLang, StringFormat)

2017-08-20 15:21 UTC, sonda2208 commented on java/lang/String/StringTest.cpp
> +    string stringValue = "string";
"Please catch string type for this value"
catch => cast?

2017-08-20 20:03 UTC, loint commented on java/lang/String/StringTest.cpp
> +    string stringValue = "string";
@thoangminh please confirm

2017-08-20 22:48 UTC, thoangminh commented on java/lang/String/StringTest.cpp
> +    string stringValue = "string";
Sorry @sonda, I made a typing mistake. That must be cast, not catch.
@loint, confirmed.

2017-08-22 22:43 UTC, ghost approved these changes

2017-08-24 14:11 UTC, dthongvl requested changes

2017-08-24 14:11 UTC, dthongvl commented on java/lang/String/String.hpp
> +                switch (lastChar) {
Can you help me explain why you use **switch** instead of **if**?
Are there any benefits?

2017-08-24 14:11 UTC, dthongvl commented on java/lang/String/String.cpp
> +String String::print(const String &format, char *value) {
Please help me replace `char *` by **string**

2017-08-24 14:11 UTC, dthongvl commented on java/lang/String/String.cpp
> +    if (length > 0)
Please help me add brackets

2017-08-24 14:11 UTC, dthongvl commented on java/lang/Double/Double.hpp
> +		class Double : public Number {		private:
Please help me add line break here

2017-08-24 14:11 UTC, dthongvl commented on java/lang/String/String.cpp
> +        if (errorCode == 0) {
Please help me shorten this with return early
`if (errorCode != 0) { ...; break;}`

2017-08-24 14:15 UTC, sonda2208 commented on java/lang/String/String.hpp
> +                switch (lastChar) {
prepare for adding '$' ... in future

2017-08-25 17:43 UTC, dthongvl approved these changes

2017-08-28 15:19 UTC, loint approved these changes

2017-08-28 15:19 UTC, merged