Java.Lang.String
tiny-express/native pull request #230
Opened 2017-08-18 07:04 UTC by TuanAnhNguyen69

2017-08-20 11:52 UTC, ghost submitted a review, later dismissed

2017-08-20 11:52 UTC, ghost commented on java/lang/String/String.cpp
> +char String::charAt(int index) const{
Missing space before {

2017-08-20 11:52 UTC, ghost commented on java/lang/String/String.cpp
> +	return static_cast<boolean>(string_endswith(this->original, suffixString.original));
Please split or shorten this line.

2017-08-20 11:52 UTC, ghost commented on java/lang/String/String.cpp
> +	//Re-calculate first character of subString
Should have a space between // and comment

2017-08-20 11:52 UTC, ghost commented on java/lang/String/String.cpp
> +	//string currentReversedString = string_reverse(subStringFromIndex);
Should have a space between // and comment

2017-08-20 11:52 UTC, thoangminh commented on java/lang/String/String.cpp
> +	// TODO fix this later, temporary use replace, need Pattern
Please add your name to TODO comment like // TODO(yourname):

2017-08-20 11:52 UTC, thoangminh commented on java/lang/String/String.cpp
> +    // TODO fix this later, temporary use replace, need Pattern
Please add your name to TODO comment like // TODO(yourname):

2017-08-20 11:52 UTC, thoangminh commented on java/lang/String/String.cpp
> +	return static_cast<boolean>(string_startswith(this->original, prefix.original));
Please split or shorten this line.

2017-08-20 11:52 UTC, thoangminh commented on java/lang/String/String.cpp
> +	if (this->original == nullptr || prefix.original == nullptr || thisOffset < 0) {
Please split or shorten this line.

2017-08-20 11:52 UTC, thoangminh commented on java/lang/String/String.cpp
> +	if (originalLength < prefixLength || thisOffset > (originalLength - prefixLength)) {
Please split or shorten this line.

2017-08-20 11:52 UTC, thoangminh commented on java/lang/String/String.cpp
> +    // TODO instanceof return false
Please add your name to TODO comment like // TODO(yourname):

2017-08-20 11:52 UTC, thoangminh commented on java/lang/String/String.cpp
> +boolean String::regionMatches(int thisOffset, String otherString, int otherOffset, int len) {
Please split or shorten this line.

2017-08-20 11:52 UTC, thoangminh commented on java/lang/String/String.cpp
> +boolean String::regionMatches(boolean ignoreCase, int thisOffset, String otherString, int otherOffset, int len) {
Please split or shorten this line.

2017-08-20 11:52 UTC, thoangminh commented on java/lang/String/String.cpp
> +void String::getChars(int sourceBegin, int sourceEnd, Array<char> &destination, int destinationBegin) {
Please split or shorten this line.

2017-08-20 11:52 UTC, thoangminh commented on java/lang/String/String.cpp
> +    // TODO fix this later, temporary, need Pattern
Please add your name to TODO comment like // TODO(yourname):

2017-08-20 11:52 UTC, thoangminh commented on java/lang/String/String.cpp
> +    String stringWithFirstRegex = this->subString(0, this->indexOf(regex) + regex.length());
Please split or shorten this line.

2017-08-20 11:52 UTC, thoangminh commented on java/lang/String/String.cpp
> +    String remainString = this->getStringFromIndex(this->indexOf(regex) + regex.length());
Please split or shorten this line.

2017-08-20 11:52 UTC, thoangminh commented on java/lang/String/String.cpp
> +    // TODO fix this later, temporary, need Pattern
Please add your name to TODO comment like // TODO(yourname):

2017-08-20 11:52 UTC, thoangminh commented on java/lang/String/String.cpp
> +    int indexOfRegexBelowLimit = string_index(this->original, regex.toString(), limit - 1);
Please split or shorten this line.

2017-08-20 11:52 UTC, thoangminh commented on java/lang/String/String.cpp
> +    String remainString = this->getStringFromIndex(indexOfRegexBelowLimit + regex.length());
Please split or shorten this line.

2017-08-20 11:52 UTC, thoangminh commented on java/lang/String/String.hpp
> +            // TODO need CharSet
Please add your name to TODO comment like // TODO(yourname):

2017-08-20 11:52 UTC, thoangminh commented on java/lang/String/String.hpp
> +            // TODO need CharSet
Please add your name to TODO comment like // TODO(yourname):

2017-08-20 11:52 UTC, thoangminh commented on java/lang/String/String.hpp
> +            // TODO need CharSet
Please add your name to TODO comment like // TODO(yourname):

2017-08-20 11:52 UTC, thoangminh commented on java/lang/String/String.hpp
> +            //String(Array<int> codePoints, int offset, int count);
Should have a space between // and comment

2017-08-20 11:52 UTC, thoangminh commented on java/lang/String/String.hpp
> +            // TODO need CharSet
Please add your name to TODO comment like // TODO(yourname):

2017-08-20 11:52 UTC, thoangminh commented on java/lang/String/String.hpp
> +            // TODO need CharSet
Please add your name to TODO comment like // TODO(yourname):

2017-08-20 11:52 UTC, thoangminh commented on java/lang/String/String.hpp
> +            //String(Array<byte> &byteArray, int offset, int length, String charsetName);
Should have a space between // and comment

2017-08-20 11:52 UTC, thoangminh commented on java/lang/String/String.hpp
> +            //static void checkBounds(Array<byte> &byteArray, int offset, int length);
Should have a space between // and comment

2017-08-20 11:52 UTC, thoangminh commented on java/lang/String/String.hpp
> +            // TODO need Character
Please add your name to TODO comment like // TODO(yourname):

2017-08-20 11:52 UTC, thoangminh commented on java/lang/String/String.hpp
> +            // TODO need Character
Please add your name to TODO comment like // TODO(yourname):

2017-08-20 11:52 UTC, thoangminh commented on java/lang/String/String.hpp
> +            // TODO need Character
Please add your name to TODO comment like // TODO(yourname):

2017-08-20 11:52 UTC, thoangminh commented on java/lang/String/String.hpp
> +            //Array<byte> getBytes(String charSetName) const;
Should have a space between // and comment

2017-08-20 11:52 UTC, thoangminh commented on java/lang/String/String.hpp
> +            void getChars(int sourceBegin, int sourceEnd, Array<char> &destination, int destinationBegin);
Please split or shorten this line.

2017-08-20 11:52 UTC, thoangminh commented on java/lang/String/String.hpp
> +            // TODO need Pattern
Please add your name to TODO comment like // TODO(yourname):

2017-08-20 11:52 UTC, thoangminh commented on java/lang/String/String.hpp
> +            // TODO need Character
Please add your name to TODO comment like // TODO(yourname):

2017-08-20 11:52 UTC, thoangminh commented on java/lang/String/String.hpp
> +            boolean regionMatches(int thisOffset, String otherString, int otherOffset, int len);
Please split or shorten this line.

2017-08-20 11:52 UTC, thoangminh commented on java/lang/String/String.hpp
> +            boolean regionMatches(boolean ignoreCase, int thisOffset, String otherString, int otherOffset, int len);
Please split or shorten this line.

2017-08-20 11:52 UTC, thoangminh commented on java/lang/String/String.hpp
> +            //CharSequence subSequence(int beginIndex, int endIndex);
Should have a space between // and comment

2017-08-20 11:52 UTC, thoangminh commented on java/lang/String/String.hpp
> +	}
Namespace should be terminated with "// namespace Lang"

2017-08-20 11:52 UTC, thoangminh commented on java/lang/String/StringTest.cpp
>  	ASSERT_STR("Food Tiny Hello World", ( textConcat0 + textConcat1 + textConcat2 ).toString());
Extra space after (. Extra space before )

2017-08-20 11:52 UTC, thoangminh commented on java/lang/String/StringTest.cpp
> +// TODO getChar run right but need Arrays.toString() to test
Please add your name to TODO comment like // TODO(yourname):

2017-08-20 11:52 UTC, thoangminh commented on java/lang/StringBuffer/StringBuffer.hpp
> +            StringBufferUnSafe &insert(int destinationOffset, CharSequence &sequence, int start, int end);
Please split or shorten this line.

2017-08-20 11:52 UTC, thoangminh commented on java/lang/StringBuffer/StringBuffer.hpp
> +            StringBuffer &insert(int destinationOffset, CharSequence &sequence, int start, int end);
Please split or shorten this line.

2017-08-20 11:52 UTC, thoangminh commented on java/lang/StringBuffer/StringBufferTest.cpp
>  TEST (JavaLang, StringBufferConstructor) {
Extra space before ( in function call

2017-08-20 11:52 UTC, thoangminh commented on java/lang/StringBuffer/StringBufferTest.cpp
>  TEST (JavaLang, StringBufferAppend) {
Extra space before ( in function call

2017-08-20 11:52 UTC, thoangminh commented on java/lang/StringBuffer/StringBufferTest.cpp
>  TEST (JavaLang, StringBufferInsertSubCharArray) {
Extra space before ( in function call

2017-08-20 11:52 UTC, thoangminh commented on java/lang/StringBuffer/StringBufferTest.cpp
>  TEST (JavaLang, StringBufferInsert) {
Extra space before ( in function call

2017-08-20 11:52 UTC, thoangminh commented on java/lang/StringBuffer/StringBufferTest.cpp
>  TEST (JavaLang, StringBufferEnsureCapacity) {
Extra space before ( in function call

2017-08-26 00:59 UTC, dthongvl requested changes

2017-08-26 00:59 UTC, dthongvl commented on java/lang/String/String.hpp
> +             * @tparam T
@tparam

2017-08-26 00:59 UTC, dthongvl commented on java/lang/StringBuffer/StringBuffer.hpp
> +        class StringBufferUnSafe : public Object, public virtual CharSequence {
Please add line break

2017-08-26 00:59 UTC, dthongvl commented on kernel/string.h
> +char *string_format(const char* format, va_list args);
Please remove this

2017-08-30 10:09 UTC, dthongvl approved these changes

2017-08-30 17:15 UTC, loint approved these changes

2017-08-30 17:18 UTC, merged